GET {{host}}/api/v1/notifications
Authorization: Bearer {{accessToken}}

> {%
client.test("Get current user notifications", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
 %}
