/*
 * Services API (hybrid variant)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"context"
	"net/http"

	"github.com/gofrs/uuid"
)

// NotificationsApiRouter defines the required methods for binding the api requests to a responses for the NotificationsApi
// The NotificationsApiRouter implementation should parse necessary information from the http request,
// pass the data to a NotificationsApiServicer to perform the required actions, then write the service results to the http response.
type NotificationsApiRouter interface {
	GetNotifications(http.ResponseWriter, *http.Request)
}

// NotificationsApiServicer defines the api actions for the NotificationsApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type NotificationsApiServicer interface {
	GetNotifications(context.Context, uuid.UUID) (ImplResponse, error)
}
