// Code generated by sqlc. DO NOT EDIT.

package database

import (
	"time"

	"github.com/gofrs/uuid"
)

type DailyDeal struct {
	Date     time.Time
	ItemID   uuid.UUID
	ItemName string
	Count    int64
	Amount   float64
}

type Top10Deal struct {
	ItemID   uuid.UUID
	ItemName string
	Count    int64
	Amount   float64
}

type TotalDailyDeal struct {
	Date   time.Time
	Count  int64
	Amount float64
}
