/*
 * Identity Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"context"
	"net/http"

	"github.com/gofrs/uuid"
)

// IdentityApiRouter defines the required methods for binding the api requests to a responses for the IdentityApi
// The IdentityApiRouter implementation should parse necessary information from the http request,
// pass the data to a IdentityApiServicer to perform the required actions, then write the service results to the http response.
type IdentityApiRouter interface {
	GetCurrentUser(http.ResponseWriter, *http.Request)
	LoginUser(http.ResponseWriter, *http.Request)
	LogoutUser(http.ResponseWriter, *http.Request)
	RegisterUser(http.ResponseWriter, *http.Request)
	UpdateCurrentUser(http.ResponseWriter, *http.Request)
}

// IdentityApiServicer defines the api actions for the IdentityApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type IdentityApiServicer interface {
	GetCurrentUser(context.Context, uuid.UUID) (ImplResponse, error)
	LoginUser(context.Context, LoginForm) (ImplResponse, error)
	LogoutUser(context.Context) (ImplResponse, error)
	RegisterUser(context.Context, RegistrationForm) (ImplResponse, error)
	UpdateCurrentUser(context.Context, uuid.UUID, UpdateForm) (ImplResponse, error)
}
