/*
 * Identity Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"context"

	"github.com/muonsoft/validation"
	"github.com/muonsoft/validation/it"
)

type LoginForm struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	AccessToken string `json:"accessToken"`
}

type RegistrationForm struct {
	Email     string `json:"email"`
	Password  string `json:"password"`
	FirstName string `json:"firstName,omitempty"`
	LastName  string `json:"lastName,omitempty"`
}

func (form RegistrationForm) Validate(ctx context.Context, validator *validation.Validator) error {
	return validator.Validate(ctx,
		validation.StringProperty("email", form.Email, it.IsNotBlank(), it.IsEmail(), it.HasLengthBetween(5, 100)),
		validation.StringProperty("password", form.Password, it.IsNotBlank(), it.HasLengthBetween(5, 20)),
		validation.StringProperty("firstName", form.FirstName, it.HasLengthBetween(1, 100)),
		validation.StringProperty("lastName", form.LastName, it.HasLengthBetween(1, 100)),
	)
}

type UpdateForm struct {
	FirstName string `json:"firstName,omitempty"`
	LastName  string `json:"lastName,omitempty"`
	Phone     string `json:"phone,omitempty"`
}

func (form UpdateForm) Validate(ctx context.Context, validator *validation.Validator) error {
	return validator.Validate(ctx,
		validation.StringProperty("firstName", form.FirstName, it.HasLengthBetween(1, 100)),
		validation.StringProperty("lastName", form.LastName, it.HasLengthBetween(1, 100)),
	)
}
