apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "billing-service.fullname" . }}
data:
  APP_ENV: "{{ .Values.application.env }}"
  MIGRATION_VERSION: "{{ .Values.migrations.version }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "billing-service.fullname" . }}
type: Opaque
data:
  BROKER_ID: {{ include "brokerId" . }}
  DATABASE_URL: {{ include "databaseUrl" . }}
  KAFKA_CONSUMER_URL: {{ include "kafkaConsumerUrl" . }}
  KAFKA_PRODUCER_URL: {{ include "kafkaProducerUrl" . }}
