/*
 * Billing service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import "github.com/gofrs/uuid"

type BillingOperation struct {
	AccountID uuid.UUID
	Amount    float64 `json:"amount"`
}
