/*
 * Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"context"
	"net/http"

	"history-service/internal/history"

	"github.com/gofrs/uuid"
	"github.com/pkg/errors"
)

// HistoryApiService is a service that implents the logic for the HistoryApiServicer
// This service should implement the business logic for every endpoint for the HistoryApi API.
// Include any external packages or services that will be required by this service.
type HistoryApiService struct {
	deals history.DealRepository
}

// NewHistoryApiService creates a default api service
func NewHistoryApiService(deals history.DealRepository) HistoryApiServicer {
	return &HistoryApiService{deals: deals}
}

// GetDealsHistory -
func (s *HistoryApiService) GetDealsHistory(ctx context.Context, userID uuid.UUID) (ImplResponse, error) {
	deals, err := s.deals.FindByUser(ctx, userID)
	if err != nil {
		return Response(http.StatusInternalServerError, nil), errors.WithMessagef(
			err,
			"failed to find deals of user %s",
			userID,
		)
	}

	return Response(http.StatusOK, deals), nil
}
