{
 "title": "Service metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Trading service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Trading API RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method, route) (rate(trading_service_request_count[1m]))"
    }
   ]
  },
  {
   "title": "Trading API Latency Q95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, route, method)(rate(trading_service_request_latency_seconds_bucket[1m]))) * 1000\n"
    }
   ]
  },
  {
   "title": "Trading Message RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (message) (rate(trading_service_message_count[1m]))"
    }
   ]
  },
  {
   "title": "Trading Message Latency Q95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, message)(rate(trading_service_message_latency_seconds_bucket[1m]))) * 1000\n"
    }
   ]
  },
  { "title": "Billing service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Billing API RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method, route) (rate(billing_service_request_count[1m]))"
    }
   ]
  },
  {
   "title": "Billing API Latency Q95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, route, method)(rate(billing_service_request_latency_seconds_bucket[1m]))) * 1000\n"
    }
   ]
  },
  {
   "title": "Billing Message RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (message) (rate(billing_service_message_count[1m]))"
    }
   ]
  },
  {
   "title": "Billing Message Latency Q95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, message)(rate(billing_service_message_latency_seconds_bucket[1m]))) * 1000\n"
    }
   ]
  },
  { "title": "Identity service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Identity API RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method, route) (rate(identity_service_request_count[1m]))"
    }
   ]
  },
  {
   "title": "Identity API Latency Q95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, route, method)(rate(identity_service_request_latency_seconds_bucket[1m]))) * 1000\n"
    }
   ]
  },
  {
   "title": "Notifications service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Notifications API RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (method, route) (rate(notification_service_request_count[1m]))"
      }
     ]
    },
    {
     "title": "Notifications API Latency Q95",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, route, method)(rate(notification_service_request_latency_seconds_bucket[1m]))) * 1000\n"
      }
     ]
    },
    {
     "title": "Notifications Message RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (message) (rate(notification_service_message_count[1m]))"
      }
     ]
    },
    {
     "title": "Notifications Message Latency Q95",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, message)(rate(notification_service_message_latency_seconds_bucket[1m]))) * 1000\n"
      }
     ]
    }
   ]
  },
  {
   "title": "History service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "History API RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (method, route) (rate(history_service_request_count[1m]))"
      }
     ]
    },
    {
     "title": "History API Latency Q95",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, route, method)(rate(history_service_request_latency_seconds_bucket[1m]))) * 1000\n"
      }
     ]
    },
    {
     "title": "History Message RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (message) (rate(history_service_message_count[1m]))"
      }
     ]
    },
    {
     "title": "History Message Latency Q95",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, message)(rate(history_service_message_latency_seconds_bucket[1m]))) * 1000\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Statistics service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Statistics API RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (method, route) (rate(statistics_service_request_count[1m]))"
      }
     ]
    },
    {
     "title": "Statistics API Latency Q95",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, route, method)(rate(statistics_service_request_latency_seconds_bucket[1m]))) * 1000\n"
      }
     ]
    },
    {
     "title": "Statistics Message RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (message) (rate(statistics_service_message_count[1m]))"
      }
     ]
    },
    {
     "title": "Statistics Message Latency Q95",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, message)(rate(statistics_service_message_latency_seconds_bucket[1m]))) * 1000\n"
      }
     ]
    }
   ]
  }
 ]
}