apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notification-service.fullname" . }}
data:
  APP_ENV: "{{ .Values.application.env }}"
  MIGRATION_VERSION: "{{ .Values.migrations.version }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notification-service.fullname" . }}
type: Opaque
data:
  DATABASE_URL: {{ include "databaseUrl" . }}
  KAFKA_CONSUMER_URL: {{ include "kafkaConsumerUrl" . }}
