apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trading-service.fullname" . }}
  labels:
    {{- include "trading-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "trading-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "trading-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "trading-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "trading-service.fullname" . }}
                  key: DATABASE_URL
            - name: KAFKA_CONSUMER_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "trading-service.fullname" . }}
                  key: KAFKA_CONSUMER_URL
            - name: KAFKA_PRODUCER_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "trading-service.fullname" . }}
                  key: KAFKA_PRODUCER_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "trading-service.fullname" . }}
                  key: REDIS_URL
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "trading-service.fullname" . }}
                  key: APP_ENV
          livenessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8000
              path: /ready
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      initContainers:
        - name: db-waiter
          image: "{{ .Values.migrations.waiter.image.repository }}:{{ .Values.migrations.waiter.image.tag }}"
          imagePullPolicy: {{ .Values.migrations.waiter.image.pullPolicy }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "trading-service.fullname" . }}
                  key: DATABASE_URL
            - name: MIGRATION_VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "trading-service.fullname" . }}
                  key: MIGRATION_VERSION
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
