apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: notification-mapping
spec:
  hostname: "*"
  prefix: "/api/v1/notifications"
  rewrite: "/api/v1/notifications"
  remainder: "/api/v1/notifications"
  service: notification-service:8000
  retry_policy:
    retry_on: "5xx"
    num_retries: 2
