apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: statistics-mapping
spec:
  hostname: "*"
  prefix: "/api/v1/statistics/"
  rewrite: "/api/v1/"
  remainder: "/api/v1/"
  service: statistics-service:8000
  retry_policy:
    retry_on: "5xx"
    num_retries: 2
