---
openapi: 3.0.0
info:
  title: Public API
  version: 1.0.0
servers:
  - url: http://example.domain/api/v1/
    description: Example Server
tags:
  - name: identity
    description: Operations about user
  - name: trading
    description: Trading operations
  - name: billing
    description: Billing operations
  - name: notifications
    description: Notifications
security:
  - JWT: []
paths:
  /identity/register:
    post:
      security: []
      tags:
        - identity
      summary: Register a user
      operationId: registerUser
      requestBody:
        description: Registration form
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/Login'
                - type: object
                  properties:
                    firstName:
                      type: string
                    lastName:
                      type: string
      responses:
        "201":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /identity/login:
    post:
      security: []
      tags:
        - identity
      summary: Login to the system
      operationId: loginUser
      requestBody:
        description: Login form
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        "200":
          description: Login response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessToken'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /identity/logout:
    post:
      tags:
        - identity
      summary: Logout from the system
      operationId: logoutUser
      responses:
        "204":
          description: Logout succeeded
  /identity/profile:
    get:
      tags:
        - identity
      description: Returns a current user profile
      operationId: getCurrentUser
      responses:
        "200":
          description: User response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - identity
      description: Update current user profile
      operationId: updateCurrentUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            examples:
              sample-user:
                summary: Example
                value:
                  firstName: Julie
                  lastName: Doe
                  email: bestjohn@doe.com
                  phone: +71004242424
      responses:
        "200":
          description: User response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /trading/purchase-orders:
    get:
      tags: [trading]
      description: Get current user purchase orders
      operationId: getPurchaseOrders
      responses:
        "200":
          description: Purchase order response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PurchaseOrder'
    post:
      tags: [trading]
      description: Create a new purchase order
      operationId: createPurchaseOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurchaseOrder'
      responses:
        "202":
          description: Purchase order created
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /trading/purchase-orders/{purchaseOrderId}/cancel:
    post:
      tags: [ trading ]
      description: Cancel a purchase order
      operationId: cancelPurchaseOrder
      parameters:
        - in: path
          name: purchaseOrderId
          schema:
            type: string
            format: uuid
          required: true
      responses:
        "200":
          description: Purchase order canceled
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /trading/sell-orders:
    get:
      tags: [trading]
      description: Get current user sell orders
      operationId: getSellOrders
      responses:
        "200":
          description: Sell order response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SellOrder'
    post:
      tags: [trading]
      description: Create a new sell order
      operationId: createSellOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SellOrder'
      responses:
        "202":
          description: Sell order created
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /trading/sell-orders/{sellOrderId}/cancel:
    post:
      tags: [ trading ]
      description: Cancel a sell order
      operationId: cancelSellOrder
      parameters:
        - in: path
          name: sellOrderId
          schema:
            type: string
            format: uuid
          required: true
      responses:
        "200":
          description: Sell order canceled
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /trading/items:
    get:
      tags: [trading]
      description: Get trading items
      operationId: getTradingItems
      responses:
        "200":
          description: Trading items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TradingItem'
    post:
      tags: [trading]
      description: Create a trading item
      operationId: createTradingItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TradingItem'
      responses:
        "201":
          description: Trading item created
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /statistics/daily-stats:
    get:
      tags: [statistics]
      description: Get daily stats
      operationId: getDailyStats
      responses:
        "200":
          description: Daily stats
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DailyStats'
  /statistics/top10:
    get:
      tags: [statistics]
      description: Get top 10
      operationId: getTop10
      responses:
        "200":
          description: Top 10 deals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Top10'

  /billing/account:
    get:
      tags: [billing]
      description: Read current user account
      operationId: getBillingAccount
      responses:
        "200":
          description: Billing account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BillingAccount'
  /billing/operations:
    get:
      tags: [billing]
      description: Read current user billing operations
      operationId: getBillingOperations
      responses:
        "200":
          description: Billing operations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BillingOperation'
  /billing/account/deposit:
    post:
      tags: [billing]
      description: Deposit money to user account
      operationId: depositMoney
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BillingOperation'
      responses:
        "204":
          description: Success
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /billing/account/withdraw:
    post:
      tags: [billing]
      description: Withdraw money from user account
      operationId: withdrawMoney
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BillingOperation'
      responses:
        "204":
          description: Success
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /notifications:
    get:
      tags: [ notifications ]
      description: Get current user notifications
      operationId: getNotifications
      responses:
        "200":
          description: Notifications response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'

components:
  securitySchemes:
    JWT:
      type: apiKey
      name: accessToken
      in: cookie
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        email:
          type: string
          format: email
          readOnly: true
        role:
          type: string
          writeOnly: true
          enum:
            - trader
            - broker
            - admin
        firstName:
          type: string
        lastName:
          type: string
        phone:
          type: string
          format: phone
    Login:
      type: object
      required: [ email, password ]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
    AccessToken:
      type: object
      required: [ accessToken ]
      properties:
        accessToken:
          type: string
    PurchaseOrder:
      type: object
      required: [ id, price ]
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        itemId:
          type: string
          format: uuid
        price:
          type: number
          minimum: 1
        commission:
          type: number
          minimum: 1
          readOnly: true
        status:
          type: string
          readOnly: true
          enum:
            - pending
            - canceled
            - paymentPending
            - paymentSucceeded
            - paymentFailed
            - approved
        createdAt:
          type: string
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true
    SellOrder:
      type: object
      required: [ id, price ]
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        itemId:
          type: string
          format: uuid
        price:
          type: number
          minimum: 1
        commission:
          type: number
          minimum: 1
          readOnly: true
        status:
          type: string
          readOnly: true
          enum:
            - pending
            - canceled
            - dealPending
            - accrualPending
            - approved
        createdAt:
          type: string
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true
    TradingItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        initialCount:
          type: integer
        initialPrice:
          type: number
        commission:
          type: number
        createdAt:
          type: string
          format: date-time
          readOnly: true
    BillingAccount:
      type: object
      properties:
        amount:
          type: number
        createdAt:
          type: string
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true
    BillingOperation:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        amount:
          type: number
        type:
          type: string
          enum:
            - deposit
            - withdraw
            - payment
            - accrual
          readOnly: true
        description:
          type: string
          readOnly: true
        createdAt:
          type: string
          format: date-time
          readOnly: true
    Notification:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        message:
          type: string
        createdAt:
          type: string
          format: date-time
          readOnly: true
    DailyStats:
      type: object
      properties:
        date:
          type: string
          format: date
        itemId:
          type: string
          format: uuid
        dealsCount:
          type: integer
        dealsAmount:
          type: number
    Error:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
