// Code generated by sqlc. DO NOT EDIT.

package database

import (
	"fmt"
	"time"

	"github.com/gofrs/uuid"
)

type DealType string

const (
	DealTypePurchase DealType = "purchase"
	DealTypeSale     DealType = "sale"
)

func (e *DealType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DealType(s)
	case string:
		*e = DealType(s)
	default:
		return fmt.Errorf("unsupported scan type for DealType: %T", src)
	}
	return nil
}

type Deal struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	ItemID      uuid.UUID
	ItemName    string
	Type        DealType
	Amount      float64
	Commission  float64
	CompletedAt time.Time
}
