name: Build docker release

on:
  release:
    types: [created]

jobs:
  release-docker:
    name: release docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set APP_VERSION env
        run: echo "APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev )" >> $GITHUB_ENV
      - name: Environment Printer
        uses: managedkaos/print-env@v1.0

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push identity service
        uses: docker/build-push-action@v2
        with:
          context: services/identity-service
          file: services/identity-service/build/package/identity-service/Dockerfile
          tags: strider2038/otus-marketplace-identity-service:latest, strider2038/otus-marketplace-identity-service:${{ env.APP_VERSION }}
          pull: true
          push: true
          build-args: APP_VERSION=${{ env.APP_VERSION }}

      - name: Build and push migrations
        uses: docker/build-push-action@v2
        with:
          context: services/identity-service
          file: services/identity-service/build/package/migrations/Dockerfile
          tags: strider2038/otus-marketplace-identity-migrations:latest, strider2038/otus-marketplace-identity-migrations:${{ env.APP_VERSION }}
          pull: true
          push: true
          build-args: APP_VERSION=${{ env.APP_VERSION }}

      - name: Build and push billing service
        uses: docker/build-push-action@v2
        with:
          context: services/billing-service
          file: services/billing-service/build/package/billing-service/Dockerfile
          tags: strider2038/otus-marketplace-billing-service:latest, strider2038/otus-marketplace-billing-service:${{ env.APP_VERSION }}
          pull: true
          push: true
          build-args: APP_VERSION=${{ env.APP_VERSION }}

      - name: Build and push migrations
        uses: docker/build-push-action@v2
        with:
          context: services/billing-service
          file: services/billing-service/build/package/migrations/Dockerfile
          tags: strider2038/otus-marketplace-billing-migrations:latest, strider2038/otus-marketplace-billing-migrations:${{ env.APP_VERSION }}
          pull: true
          push: true
          build-args: APP_VERSION=${{ env.APP_VERSION }}

      - name: Build and push notification service
        uses: docker/build-push-action@v2
        with:
          context: services/notification-service
          file: services/notification-service/build/package/notification-service/Dockerfile
          tags: strider2038/otus-marketplace-notification-service:latest, strider2038/otus-marketplace-notification-service:${{ env.APP_VERSION }}
          pull: true
          push: true
          build-args: APP_VERSION=${{ env.APP_VERSION }}

      - name: Build and push migrations
        uses: docker/build-push-action@v2
        with:
          context: services/notification-service
          file: services/notification-service/build/package/migrations/Dockerfile
          tags: strider2038/otus-marketplace-notification-migrations:latest, strider2038/otus-marketplace-notification-migrations:${{ env.APP_VERSION }}
          pull: true
          push: true
          build-args: APP_VERSION=${{ env.APP_VERSION }}

      - name: Build and push trading service
        uses: docker/build-push-action@v2
        with:
          context: services/trading-service
          file: services/trading-service/build/package/trading-service/Dockerfile
          tags: strider2038/otus-marketplace-trading-service:latest, strider2038/otus-marketplace-trading-service:${{ env.APP_VERSION }}
          pull: true
          push: true
          build-args: APP_VERSION=${{ env.APP_VERSION }}

      - name: Build and push migrations
        uses: docker/build-push-action@v2
        with:
          context: services/trading-service
          file: services/trading-service/build/package/migrations/Dockerfile
          tags: strider2038/otus-marketplace-trading-migrations:latest, strider2038/otus-marketplace-trading-migrations:${{ env.APP_VERSION }}
          pull: true
          push: true
          build-args: APP_VERSION=${{ env.APP_VERSION }}

      - name: Build and push history service
        uses: docker/build-push-action@v2
        with:
          context: services/history-service
          file: services/history-service/build/package/history-service/Dockerfile
          tags: strider2038/otus-marketplace-history-service:latest, strider2038/otus-marketplace-history-service:${{ env.APP_VERSION }}
          pull: true
          push: true
          build-args: APP_VERSION=${{ env.APP_VERSION }}

      - name: Build and push migrations
        uses: docker/build-push-action@v2
        with:
          context: services/history-service
          file: services/history-service/build/package/migrations/Dockerfile
          tags: strider2038/otus-marketplace-history-migrations:latest, strider2038/otus-marketplace-history-migrations:${{ env.APP_VERSION }}
          pull: true
          push: true
          build-args: APP_VERSION=${{ env.APP_VERSION }}

      - name: Build and push statistics service
        uses: docker/build-push-action@v2
        with:
          context: services/statistics-service
          file: services/statistics-service/build/package/statistics-service/Dockerfile
          tags: strider2038/otus-marketplace-statistics-service:latest, strider2038/otus-marketplace-statistics-service:${{ env.APP_VERSION }}
          pull: true
          push: true
          build-args: APP_VERSION=${{ env.APP_VERSION }}

      - name: Build and push migrations
        uses: docker/build-push-action@v2
        with:
          context: services/statistics-service
          file: services/statistics-service/build/package/migrations/Dockerfile
          tags: strider2038/otus-marketplace-statistics-migrations:latest, strider2038/otus-marketplace-statistics-migrations:${{ env.APP_VERSION }}
          pull: true
          push: true
          build-args: APP_VERSION=${{ env.APP_VERSION }}
